config setup
    charondebug="ike 1, knl 1, cfg 0"

conn cusco-lima
    keyexchange=ikev2
    authby=secret
    left=192.168.10.2
    leftsubnet=10.10.1.0/24
    right=192.168.20.4
    rightsubnet=172.31.1.0/24,172.32.1.0/24
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256-modp2048!
    auto=start
    dpdaction=restart
    dpddelay=10s
